services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grants
    ports:
      - "5432:5432"
    volumes:
      - grants-db:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/grants
    volumes:
      - ./backend:/app

volumes:
  grants-db: